name: alaska2
channels:
  - pytorch
  - plotly
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pytorch
  - pip
  - albumentations
  - matplotlib
  - pandas
  - pyyaml
  - requests
  - scikit-image
  - scipy
  - torchvision
  - tqdm
  - urllib3
  - awscli
  - pyhamcrest
  - cython
  - h5py
  - ncurses
  - jupyter
  - ipykernel
  - statsmodels
  - pillow
  - scikit-learn
  - testpath
  - mkl
  - mkl-include
  - mkl-service
  - mkl_fft
  - mkl_random
  - blas
  - numpy
  - cuda100
  - cudatoolkit=10.0
  - plotly
  - jupyterlab
  - ignite
  - feather-format
  - nodejs=13.10.1
  - ipywidgets=7.5.1
  - rapids=0.14
  - pip:
    - segmentation-models-pytorch
    - mlflow
    - tables
    - dacite
    - click
    - easydict
    - utm
    - torchsummary
    - tensorboardX
    - optuna
    - pfio
    - yacs
    - git+https://github.com/rwightman/pytorch-image-models#egg=timm-0.1.26
    - seaborn
    - lightgbm
